services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "9229:9229"

    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development # ## - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=jiyoung
      - DB_PASS=202486
      - DB_NAME=chatjam
      - DB_SSL=false
      - DOCKERIZED=true
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: jiyoung
      POSTGRES_PASSWORD: 202486
      POSTGRES_DB: chatjam
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # remove this in production

volumes:
  pgdata:
# need to modify this file when deploying
